services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Basilicom\DataQualityBundle\Controller\:
      resource: '../../Controller'
      public: true
      tags: ['controller.service_arguments']

    Basilicom\DataQualityBundle\Command\:
      resource: '../../Command'
      public: true
      tags: ['command.service_arguments']

    Basilicom\DataQualityBundle\Tools\Installer:
      public: true
      arguments:
        $bundle: "@=service('kernel').getBundle('DataQualityBundle')"

    Basilicom\DataQualityBundle\DefinitionsCollection\Factory\FieldDefinitionFactory:
      public: true

    Basilicom\DataQualityBundle\Service\DataQualityService:
      public: true

    Basilicom\DataQualityBundle\Provider\DataQualityProvider:
      public: true

    Basilicom\DataQualityBundle\Model\Listener\ObjectPostUpdateListener:
      tags:
        - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onPostUpdate }

    Basilicom\DataQualityBundle\Command\UpdateDataQualityCommand:
      tags:
        - { name: console.command, command: 'dataquality:update' }


    #
    # custom Renderer
    #
    custom_renderer.data_quality_config:
      class: Basilicom\DataQualityBundle\Model\Renderer\DataQualityConfigRenderer
      public: true

    #
    # option providers
    #
    options_provider.object_classes:
      class: Basilicom\DataQualityBundle\Model\Provider\ObjectClassesProvider
      public: true

    options_provider.object_fields:
      class: Basilicom\DataQualityBundle\Model\Provider\ObjectFieldsProvider
      public: true

    options_provider.definitions:
      class: Basilicom\DataQualityBundle\Model\Provider\DefinitionsProvider
      public: true
